behappy_company_data_plugin_admin:
    resource: |
        alias: behappy_company_data_plugin.company_data
        path: company-data
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['show']
        redirect: update
        grid: behappy_company_data_plugin.company_data
        permission: true
        vars:
            all:
                subheader: behappy_company_data_plugin.ui.manage_company_data
            index:
                icon: share alternate
    type: sylius.resource