BeHappy\SyliusCompanyDataPlugin\Entity\BaseCompanyData:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: false
            length: 127
        addressNumber:
            type: string
            nullable: false
            length: 31
        addressStreet:
            type: string
            nullable: false
            length: 255
        addressStreetExtension:
            type: string
            nullable: true
            length: 255
        addressZipCode:
            type: string
            nullable: false
            length: 15
        addressCountry:
            type: string
            nullable: false
            length: 63
        vatNumber:
            type: string
            nullable: false
            length: 63
        siret:
            type: string
            nullable: true
            length: 63
        information:
            type: text
            nullable: true
        addressCity:
            type: string
            nullable: false
            length: 255
