BeHappy\SyliusCompanyDataPlugin\Entity\CompanyData:
    type: mappedSuperclass
    table: behappy_company_data
    manyToMany:
        channels:
            targetEntity: Sylius\Component\Core\Model\Channel
            joinTable:
                name: behappy_company_data_channel
                joinColumns:
                    - name: company_data
                      referencedColumnName: id
